### ISSUE TITLE
Design: mobile menu overlay

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#77] opened 2021-02-27 14:39 UTC
[Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1713%3A5970)

**Comment by mjcarsjens** [comment] 2021-04-09 11:31
Duplicate of #75

**Closed** 2022-03-02 13:26 UTC
Labels: duplicate
