### ISSUE TITLE
Design: Timeline

### ISSUE THREAD

**Issue by GewoonMaarten** [nl-design-system/denhaag#61] opened 2021-02-27 14:29 UTC
Create a timeline component according to [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1616%3A6543).

**Comment by mjcarsjens** [comment] 2021-04-09 11:06
duplicate of https://github.com/Gemeente-DenHaag/denhaag-component-library/issues/110

**Closed** 2021-12-08 07:49 UTC
Labels: duplicate
