### ISSUE TITLE
No matching version found

### ISSUE THREAD

**Issue by JostCrow** [nl-design-system/denhaag#460] opened 2021-10-13 13:30 UTC
Hello,

When I try to install this repository via npm I will get the following error. 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @gemeente-denhaag/baseprops@^0.2.3-alpha.38.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@gemeente-denhaag/denhaag-component-library'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jorik/.npm/_logs/2021-10-13T13_25_06_948Z-debug.log
```

However when I look on [npmjs.com](https://www.npmjs.com/search?q=gemeente-denhaag%20base) is says that latest version is `0.2.3-alpha.38`, However when you go to to the [detail page](https://www.npmjs.com/package/@gemeente-denhaag/baseprops) is only shows version `0.2.3-alpha.36`. This breaks the installation of this package.

**Comment by bddjong** [comment] 2021-10-14 06:45
Hi @JostCrow. Thank you for reporting this issue. This should be fixed after a republish today. It was caused by a publish during an NPM outage.

**Comment by bddjong** [comment] 2021-10-15 09:49
The packages can be found again from version `alpha.39` and higher

**Closed as completed** 2021-10-15 09:49 UTC
